#!/bin/bash
set -euo pipefail
IFS=$'\n\t'


# adding necessary config
mkdir -p "$(pwd)/.cargo"
cat << EOF > "$(pwd)/.cargo/config"
[target.arm-unknown-linux-gnueabihf]
linker = "/rpi_tools/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
EOF

WORKDIR="/work"
docker run --rm -t \
       -u "$(id -u):$(id -g)" \
       -e "HOME=${WORKDIR}" \
       -e "PKG_CONFIG_ALLOW_CROSS=1" \
       -w "${WORKDIR}" \
       -v "$(pwd):${WORKDIR}" \
       -v "${HOME}/.cargo/registry:/usr/local/cargo/registry" \
       rust_armv6

head -n -2 .cargo/config > temp.txt && mv temp.txt .cargo/config
